### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: gnu/trove/strategy/HashingStrategy

### ISSUE THREAD

**Issue by GeniusPudding** [JordanSamhi/Difuzer#1]
![image](https://user-images.githubusercontent.com/55935566/162113611-5e560736-ed28-45b3-bf70-7c34e581b8b8.png)

Hi, I'm a beginner of maven and now studying android analysis tools based on soot.
I have installed this tool by "mvn clean install". 
However I got an Exception during the evecution.
Is there anything be misconfigured?

Thanks!

**Comment by JordanSamhi** [comment]
Hi @GeniusPudding,

Could you check the Java version you are using? Difuzer (and Soot-based tools) works better with Java 8.

**Comment by GeniusPudding** [comment]
Thanks for your reponse!
![image](https://user-images.githubusercontent.com/55935566/162171643-70c43be9-0bae-4bd9-badc-80348c3e86a2.png)
I also try to install Difuzer in docker image with openjdk version "1.8.0_292".
However it still fail during the maven building process

**Comment by GeniusPudding** [comment]
I'll keep trying to downgrade my java version on my ubuntu and solve the Exception during the execution. 
Thanks!

**Comment by GeniusPudding** [comment]
![image](https://user-images.githubusercontent.com/55935566/162220321-e87975ef-b4fe-45f9-bec9-acfed0ac4996.png)
![image](https://user-images.githubusercontent.com/55935566/162220618-3d9e8fba-815d-4a86-82ba-ea2c2468b678.png)

Still the same Exception on my linux workstation
I think I used JAVA 8 and re-installed this tool by maven

**Comment by JordanSamhi** [comment]
HI @GeniusPudding,

I spotted the problem with the compilation process, I pushed some modifications, could you try again?

Thank you for noticing

**Comment by GeniusPudding** [comment]
I've got a new Exception when I execute the current version 
![image](https://user-images.githubusercontent.com/55935566/162224356-d242d48b-573a-44be-8297-ac1e481c9f12.png)

Is there any of my package version wrong? Soot, or others

**Comment by JordanSamhi** [comment]
I juste tested the latest version, it works on my side, could you share the sample with which you tested?
<img width="849" alt="Screenshot 2022-04-07 at 11 14 53 AM" src="https://user-images.githubusercontent.com/35679728/162270759-77274a4f-0b3b-4d85-8640-79fa72aa13c4.png">

**Comment by GeniusPudding** [comment]
https://drive.google.com/file/d/18J8E82-aS0E4IsXhFqqaYWbyMjpTPJ62/view?usp=sharing

Downloaded from the AndroZoo dataset (listed in https://github.com/JordanSamhi/Difuzer/blob/master/artefacts/datasets/malwares.txt)

**Comment by GeniusPudding** [comment]
Oh sorry this file was scanned by google malware policy
"00F223C81F0AEA7D61FA00EDC2746808F6898375CAC18635C460D5BBE9DEECA4.apk"
listed in https://github.com/JordanSamhi/Difuzer/blob/master/artefacts/datasets/malwares.txt

**Comment by JordanSamhi** [comment]
Ok, my bad, I should not have updated the pom.xml with the latest version of Flowdroid and Soot, it broke something. I will let the versions I used while developing Difuzer.
You can now git pull again, and follow the instructions in the README to build the executable with the following commands:
```cd Difuzer
mvn clean install:install-file -Dfile=libs/soot-infoflow-android-classes.jar -DgroupId=de.tud.sse -DartifactId=soot-infoflow-android -Dversion=2.7.1 -Dpackaging=jar
mvn clean install:install-file -Dfile=libs/soot-infoflow-classes.jar -DgroupId=de.tud.sse -DartifactId=soot-infoflow -Dversion=2.7.1 -Dpackaging=jar
mvn clean install
```

I just tested with your sample, it works.

Let me know,

**Comment by GeniusPudding** [comment]
![image](https://user-images.githubusercontent.com/55935566/162356917-778ac93d-ce95-40ce-a11b-7316db01275d.png)

I installed the latest version and found "Exception in thread "main" java.lang.NoClassDefFoundError: gnu/trove/strategy/HashingStrategy" again

![image](https://user-images.githubusercontent.com/55935566/162357136-0c360079-ac25-41a8-beec-585ca080185a.png)
![image](https://user-images.githubusercontent.com/55935566/162357409-94346a9d-d160-48a5-9465-34bd8ca1de80.png) Ubuntu 18.04

Is that caused by my JAVA version? I'm really not familiar with JAVA developing.
Still thank you very much for your reply!

**Comment by JordanSamhi** [comment]
The problem is related to this one: https://github.com/secure-software-engineering/FlowDroid/issues/216

I need to fix that, it is because at the time of development, I could not find a de.tud.sse:soot-infoflow-android on maven, I had to import it manually, that is why all these maven install commands.

In the meantime, you can try to import trove4j in the project and try again: https://mvnrepository.com/artifact/net.sf.trove4j/trove4j

**Comment by GeniusPudding** [comment]
![image](https://user-images.githubusercontent.com/55935566/162384005-260fd770-e8c0-4bbd-9e1f-1edb9caeb4e9.png)

After added https://mvnrepository.com/artifact/net.sf.trove4j/trove4j/3.0.3 and re-installed, it works!

Thanks to you for all of your help and replies! 
I'll start to test on more AndroZoo samples, and maybe more study on how to develop a soot project

**Comment by JordanSamhi** [comment]
Great, perfect! 👍
